In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
# создаем датафрейм
df = pd.read_csv('/content/drive/MyDrive/Data/posts_ai_telegram_cleaned.csv', encoding='utf-8')

In [ ]:
df

id_post                       date  \
0        2017  2025-03-22 07:02:11+00:00   
1        2016  2025-03-21 16:06:01+00:00   
2        2015  2025-03-21 15:40:09+00:00   
3        2014  2025-03-21 15:39:59+00:00   
4        2013  2025-03-20 09:05:47+00:00   
...       ...                        ...   
5881       34  2017-11-15 07:51:33+00:00   
5882       33  2017-11-15 07:49:44+00:00   
5883       31  2017-11-13 08:10:28+00:00   
5884       30  2017-11-10 10:15:37+00:00   
5885        9  2017-11-03 10:15:13+00:00   

                                                   text   views  reactions  \
0     Немного о том, что я, редактор Individuum'а, в...   820.0         39   
1     🙅 Книга-эксперимент о мытарствах современного ...  1386.0         89   
2     🥴 Новое путешествие под кожу читателя от автор...  1444.0         64   
3     Сегодня говорим «да» предзаказам на две книги,...  1243.0         30   
4     💰 Ишь, какие мы деловые — попали в [**шортлист...  1643.0         59   
...                                                 ...     ...        ...   
5881             Так будет выглядеть наш следующий год!  1172.0          0   
5882  В 2016 году к 12 апреля художница Анастасия Пр...  1105.0          0   
5883  В далекой-далекой Коста-Рике завершилась **Все...  1047.0          2   
5884  #кино в ИТМО\n13 и 14 ноября в Университете ИТ...  1139.0          2   
5885  Всем прив! Это официальный и не очень телеграм...  1048.0          3   

      comments                                       cleaned_text  
0            1  немного редактор вообще делать красноуральск с...  
1            3  книга-эксперимент мытарство современный художн...  
2            6  новый путешествие кожа читатель автор бестселл...  
3            0  сегодня говорить предзаказ книга который говорить  
4            2  ишь деловой попасть шортлист премия деловой кн...  
...        ...                                                ...  
5881         0                        выглядеть наш следующий год  
5882         0  год апрель художница анастасия просочкин нарис...  
5883         0  далёкий-далёкий коста-рика завершиться всемирн...  
5884         0  кино итмый ноябрь университет итмый пройти фес...  
5885         0  весь прива это официальный очень телеграм-кана...  

[5886 rows x 7 columns]

BOW

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()
#удаляем строки с nan
df = df.dropna(subset=['cleaned_text'])
#векторизуем сразу весь корпус
X = vectorizer.fit_transform(df['cleaned_text']).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X.shape

(5838, 31904)

In [ ]:
#cохранение векторов в файл .npy
np.save('/content/drive/MyDrive/Data/vectors_bow.npy', X)


TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
#векторизуем сразу весь корпус
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['cleaned_text']).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#cохранение векторов в файл .npy
np.save('/content/drive/MyDrive/Data/vectors_tfidf.npy', X)

Word2Vec

In [ ]:
!pip install gensim > None

In [ ]:
#принудительная перезагрузка среды выполнения. После перезагрузки нужно запускать только последующий код
import os
os.kill(os.getpid(), 9)

In [ ]:
import nltk
import nltk.tokenize
from nltk import word_tokenize
from gensim.models import Word2Vec
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
df = df.dropna(subset=['cleaned_text'])
l = df.cleaned_text.to_list()
x_token = [nltk.word_tokenize(text) for text in l]
x_token

[['немного',
  'редактор',
  'вообще',
  'делать',
  'красноуральск',
  'стать',
  'первый',
  'восемь',
  'уральский',
  'моногород',
  'который',
  'принимать',
  'серия',
  'фестиваль',
  'объединять',
  'локальный',
  'идентичность',
  'наука',
  'культура',
  'сайт',
  'подробность',
  'водиться',
  'книга',
  'рассказывать',
  'книжный',
  'ярмарка',
  'стол',
  'книга',
  'разный',
  'издательство',
  'представитель',
  'правда',
  'весь',
  'пятеро',
  'включая',
  'остальной',
  'брать',
  'прекрасный',
  'ребята',
  'кофе',
  'книга',
  'измерение',
  'организатор',
  'сегодня',
  'второй',
  'день',
  'фестиваль',
  'запланировать',
  'лекция',
  'палеоэкология',
  'техника',
  'обработка',
  'металл',
  'концерт',
  'пётр',
  'термена',
  'правнук',
  'изобретатель',
  'терменвокс',
  'встреча',
  'алексей',
  'сальниковый',
  'несколько',
  'мастер-класс',
  'школьник',
  'число',
  'классный',
  'название',
  'прочесть',
  'свой',
  'город',
  'научный',
  'шоу',
  'биоло

In [ ]:
#обучение модели Word2Vec
w2v_model = Word2Vec(sentences=x_token, vector_size=300, window=5, min_count=1, epochs=300)

In [ ]:
w2v_model.save('/content/drive/MyDrive/W2V_pretrained.bin')

In [ ]:
# Создаем объект модели перед загрузкой
w2v_model = Word2Vec()
w2v_model = Word2Vec.load('/content/drive/MyDrive/W2V_pretrained.bin')

In [ ]:
vocab = w2v_model.wv.key_to_index
vocab_size = len(vocab)
print(f"Количество уникальных слов в словаре: {vocab_size}")
print(vocab)

Количество уникальных слов в словаре: 32949
{'это': 0, 'книга': 1, 'который': 2, 'год': 3, 'наш': 4, 'всё': 5, 'свой': 6, 'весь': 7, 'новый': 8, 'итмый': 9, 'ещё': 10, 'мочь': 11, 'искусство': 12, 'человек': 13, 'история': 14, 'первый': 15, 'самый': 16, 'время': 17, 'жизнь': 18, 'работа': 19, 'день': 20, 'стать': 21, 'проект': 22, 'мир': 23, 'хороший': 24, 'автор': 25, 'читать': 26, 'большой': 27, 'сегодня': 28, 'подкаст': 29, 'очень': 30, 'россия': 31, 'рассказывать': 32, 'друг': 33, 'программа': 34, 'выпуск': 35, 'работать': 36, 'сделать': 37, 'вместе': 38, 'вопрос': 39, 'каждый': 40, 'ждать': 41, 'рассказать': 42, 'университет': 43, 'учёный': 44, 'художник': 45, 'почему': 46, 'хотеть': 47, 'знать': 48, 'студент': 49, 'наука': 50, 'научный': 51, 'ваш': 52, 'роман': 53, 'говорить': 54, 'материал': 55, 'современный': 56, 'просто': 57, 'новость': 58, 'русский': 59, 'событие': 60, 'издание': 61, 'слово': 62, 'место': 63, 'фильм': 64, 'ребёнок': 65, 'книжный': 66, 'ссылка': 67, 'писать': 

In [ ]:
vectors_texts = []
for text in x_token:
    vectors_word = []
    for word in text:
        if word in w2v_model.wv:  #проверяем, есть ли слово в модели
            vectors_word.append(w2v_model.wv[word])
        else:
            vectors_word.append(np.zeros(w2v_model.vector_size))
    #усредняем вектора
    vector_text = np.mean(vectors_word, axis=0)
    vectors_texts.append(vector_text)

vectors_array = np.array(vectors_texts)
np.save('/content/drive/MyDrive/Data/vectors_w2v.npy', vectors_array)

In [ ]:
vectors_array

array([[ 0.34327167, -0.14428928, -0.12260389, ...,  0.17937243,
         0.12531067,  0.46682388],
       [ 0.04558151, -0.35105452,  0.06702286, ..., -0.17052728,
         0.22390136,  0.95037067],
       [ 0.12200719, -0.16519648, -0.51604086, ...,  0.12793829,
         0.14654893,  0.30570376],
       ...,
       [ 0.2845983 ,  0.08891457,  0.93987155, ..., -0.2466586 ,
        -0.61692864,  0.46544695],
       [ 0.28498244,  0.14119944,  0.60914177, ..., -1.4597934 ,
         0.18226525, -0.6057591 ],
       [ 0.2795401 , -0.4048951 ,  0.8534904 , ..., -1.0581628 ,
         0.1851479 ,  1.1868566 ]], dtype=float32)

In [ ]:
#кол-во и размер векторов
vectors_array.shape

(5838, 300)